version: '2.2'

services:

  frontend:
    image: richard_fe:1.0
    ports:
      - "8000:8000"
    networks:
        - net_app

  backend:
    image: richard_be:1.0
    ports:
        - "8080:8080"
    networks:
        - net_app
    depends_on:
        - frontend
networks:
  net_app:
    driver: bridge
